name: release-notification

on:
    release:
        types:
            - published

jobs:
    release-notification:
        name: Release notification
        runs-on: ubuntu-latest
        strategy:
            matrix:
                to-emails:
                    - gerald@postpay.asia
        
        steps:
            - name: Send email
              uses: dawidd6/action-send-mail@v3.12.0
              with:
                # Specify connection via URL (replaces server_address, server_port, secure,
                # username and password)
                #
                # Format:
                #
                #  * smtp://user:password@server:port
                #  * smtp+starttls://user:password@server:port
                connection_url: smtp://${{ secrets.EMAIL_USERNAME }}:${{ secrets.EMAIL_PASSWORD }}@${{ secrets.EMAIL_SERVER }}:465
                # Required mail server address if not connection_url:
                server_address: ${{ secrets.EMAIL_SERVER }}
                # Server port, default 25:
                server_port: 465
                # Optional whether this connection use TLS (default is true if server_port is 465)
                secure: true
                # Optional (recommended) mail server username:
                username: ${{ secrets.EMAIL_USERNAME }}
                # Optional (recommended) mail server password:
                password: ${{ secrets.EMAIL_PASSWORD }}
                # Required mail subject:
                subject: New Release ${{ github.repository }}:${{ github.ref_name }}
                # Required recipients' addresses:
                to: ${{ matrix.to-emails }}
                # Required sender full name (address can be skipped):
                from: Github Action Bot # <user@example.com>
                # Optional plain body:
                html_body: |
                    ${{ github.event.release.body }}
                
                # Optional unsigned/invalid certificates allowance:
                ignore_cert: true
                # Optional converting Markdown to HTML (set content_type to text/html too):
                convert_markdown: true
                # Optional priority: 'high', 'normal' (default) or 'low'
                priority: low
                # Optional nodemailerlog: true/false
                nodemailerlog: true
                # Optional nodemailerdebug: true/false if true lognodem will also be set true
                nodemailerdebug: true
